test: 근무자 출/퇴근 repository 단위 테스트 & 구현
* test: 정상 출근 단위 테스트

* test: 정상 출근 단위 테스트 수정

* test: 지각, 퇴근 단위 테스트

* test: 실패 테스트(CI 테스트)

* fix: 실패 테스트 삭제

diff --git a/.github/workflows/gradleTest.yml b/.github/workflows/gradleTest.yml
--- a/.github/workflows/gradleTest.yml
+++ b/.github/workflows/gradleTest.yml
@@ -29,7 +29,14 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Build with Gradle
-        run: ./gradlew customTest 
+        run: ./gradlew clean build
+      - name: Check Test Results
+        run: |
+          TEST_RESULT=$(./gradlew test --quiet)
+          if [[ $TEST_RESULT == *"FAILURE"* ]]; then
+            echo "::error::Unit tests failed. Please check the code and try again."
+            exit 1
+          fi
       - name: Notify Slack
         if: always()
         uses: 8398a7/action-slack@v2.6.0
@@ -47,47 +54,5 @@ jobs:
       - name: Prevent merge on failure
         if: ${{ failure() }}
         run: echo "::set-output name=mergeable::false"
-      - name: Comment on pull request If Failed
-        uses: actions/github-script@0.2.0
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          script: |
-            const ref = "${{github.ref}}"
-            const pull_number = Number(ref.split("/")[2])
-
-            await github.pulls.createReview({
-              ...context.repo,
-              pull_number,
-              body: "A failed test code exists. Please check the code again.",
-              event: "REQUEST_CHANGES"
-            })
-
-            await github.pulls.update({
-             ...context.repo,
-             pull_number,
-             state: "open"
-            })  
-           
-            core.setFailed("A failed test code exists. Merge is not allowed.")
-        if: failure()
-      - name: Comment on pull request If Success
-        uses: actions/github-script@0.2.0
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const ref = "${{ github.ref }}"
-            const pull_number = Number(ref.split("/")[2])
-            const { data: pullRequest } = await github.pulls.get({
-              ...context.repo,
-              pull_number
-            })
-            const commit_id = pullRequest.head.sha
-            await github.issues.createComment({
-              ...context.repo,
-              issue_number: pull_number,
-              body: "Build Success!",
-              commit_id
-            })
-        if: success()
 
 
