fix: 버그 수정

diff --git a/.github/workflows/gradleTest.yml b/.github/workflows/gradleTest.yml
--- a/.github/workflows/gradleTest.yml
+++ b/.github/workflows/gradleTest.yml
@@ -19,55 +19,56 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-    - name: Build with Gradle
-      run: ./gradlew customTest 
-    - name: Notify Slack on failure
-      if: ${{ failure() }}
-      uses: 8398a7/action-slack@v2.6.0
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        status: ${{ job.status }}
-        message: |
-          Job: ${{ github.job }}
-          Repository: ${{ github.repository }}
-          Commit: ${{ github.sha }}
-          Event: ${{ github.event_name }}
-          Branch: ${{ github.ref }}
-    - name: Prevent merge on failure
-      if: ${{ failure() }}
-      run: echo "::set-output name=mergeable::false"
-    - name: Update pull request mergeability status
-      if: always()
-      run: |
-        if [ "${{ steps.prevent_merge.outputs.mergeable }}" == "false" ]; then
-          echo "The pull request contains failed tests. Merging is not allowed."
-          exit 1
-        fi
-    - name: Comment on pull request
-      if: always()
-      uses: actions/github-script@v4
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const { data: pullRequest } = await github.rest.pulls.get({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            pull_number: context.payload.pull_request.number
-          });
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+      - name: Build with Gradle
+        run: ./gradlew customTest 
+      - name: Notify Slack on failure
+        if: ${{ failure() }}
+        uses: 8398a7/action-slack@v2.6.0
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          status: ${{ job.status }}
+          message: |
+            Job: ${{ github.job }}
+            Repository: ${{ github.repository }}
+            Commit: ${{ github.sha }}
+            Event: ${{ github.event_name }}
+            Branch: ${{ github.ref }}
+      - name: Prevent merge on failure
+        if: ${{ failure() }}
+        run: echo "::set-output name=mergeable::false"
+      - name: Update pull request mergeability status
+        if: always()
+        run: |
+          if [ "${{ steps.prevent_merge.outputs.mergeable }}" == "false" ]; then
+            echo "The pull request contains failed tests. Merging is not allowed."
+            exit 1
+          fi
+      - name: Comment on pull request
+        if: always() && github.event.pull_request
+        uses: actions/github-script@v4
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { data: pullRequest } = await github.rest.pulls.get({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              pull_number: context.payload.pull_request.number
+            });
 
-          await github.rest.issues.createComment({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: pullRequest.number,
-            body: 'The tests have completed. You can find the status in the workflow logs.'
-          });
+            await github.rest.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: pullRequest.number,
+              body: 'The tests have completed. You can find the status in the workflow logs.'
+            });
+
